spring.application.name=api-da-gopro

# Configuracao do Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/go_pro_db
spring.datasource.username=admin
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracao do Hibernate (JPA)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuracao do Pool de Conexoes (opcional, melhora desempenho)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000