-- Dados de minist?rios e secretarias importados de planilhas oficiais na raiz do projeto.
-- Fonte principal: BASE DE DADOS - TEDS (2).xlsx / aba BASE_SECRETARIAS_MINISTERIOS.
-- Fonte de valida??o: Minist?rios (1).xlsx / aba Planilha1.

WITH ministry_source(name, sigla) AS (
    VALUES
        ('Advocacia-Geral da União', 'AGU'),
        ('Casa Civil', 'CC'),
        ('Controladoria-Geral da União', 'CGU'),
        ('Gabinete de Segurança Institucional', 'GSI'),
        ('Ministério da Agricultura e Pecuária', 'MAPA'),
        ('Ministério das Cidades', 'MCID'),
        ('Ministério das Comunicações', 'MCOM'),
        ('Ministério da Ciência, Tecnologia e Inovação', 'MCTI'),
        ('Ministério da Defesa', 'MD'),
        ('Ministério do Desenvolvimento Agrário e Agricultura Familiar', 'MDA'),
        ('Ministério dos Direitos Humanos e da Cidadania', 'MDHC'),
        ('Ministério do Desenvolvimento, Indústria, Comércio e Serviços', 'MDIC'),
        ('Ministério do Desenvolvimento e Assistência Social, Família e Combate à Fome', 'MDS'),
        ('Ministério da Educação', 'MEC'),
        ('Ministério do Empreendedorismo da Microempresa e da Empresa de Pequeno Porte', 'MEMP'),
        ('Ministério do Esporte', 'MESP'),
        ('Ministério da Fazenda', 'MF'),
        ('Ministério da Gestão e da Inovação em Serviços Públicos', 'MGI'),
        ('Ministério da Integração e do Desenvolvimento Regional', 'MIDR'),
        ('Ministério da Cultura', 'MINC'),
        ('Ministério da Igualdade Racial', 'MIR'),
        ('Ministério da Justiça e Segurança Pública', 'MJSP'),
        ('Ministério do Meio Ambiente e Mudança do Clima', 'MMA'),
        ('Ministério de Minas e Energia', 'MME'),
        ('Ministério das Mulheres', 'MMULHERES'),
        ('Ministério da Pesca e Aquicultura', 'MPA'),
        ('Ministério dos Povos Indígenas', 'MPI'),
        ('Ministério do Planejamento e Orçamento', 'MPO'),
        ('Ministério de Portos e Aeroportos', 'MPOR'),
        ('Ministério da Previdência Social', 'MPS'),
        ('Ministério das Relações Exteriores', 'MRE'),
        ('Ministério da Saúde', 'MS'),
        ('Ministério dos Transportes', 'MT'),
        ('Ministério do Trabalho e Emprego', 'MTE'),
        ('Ministério do Turismo', 'MTUR'),
        ('Secretaria de Comunicação Social', 'SECOM'),
        ('Secretaria-Geral da Presidência', 'SGPR'),
        ('Secretaria de Relações Institucionais', 'SRI')
), normalized_ministry AS (
    SELECT
        regexp_replace(trim(name), '\s+', ' ', 'g') AS name,
        upper(regexp_replace(trim(sigla), '\s+', '', 'g')) AS sigla
    FROM ministry_source
), updated_ministry AS (
    UPDATE public_agencies pa
    SET
        name = nm.name,
        sigla = nm.sigla,
        is_client = TRUE,
        public_agency_type = 'MINISTERIO',
        is_active = TRUE,
        updated_at = NOW(),
        updated_by = COALESCE(pa.updated_by, 1)
    FROM normalized_ministry nm
    WHERE pa.public_agency_type = 'MINISTERIO'
      AND upper(trim(pa.sigla)) = nm.sigla
    RETURNING pa.id
)
INSERT INTO public_agencies (
    code, sigla, name, cnpj, is_client, public_agency_type,
    email, phone, address, contact_person, city, state, is_active, created_by, created_at
)
SELECT
    NULL,
    nm.sigla,
    nm.name,
    NULL,
    TRUE,
    'MINISTERIO',
    NULL, NULL, NULL, NULL, NULL, NULL,
    TRUE,
    1,
    NOW()
FROM normalized_ministry nm
WHERE NOT EXISTS (
    SELECT 1
    FROM public_agencies pa
    WHERE pa.public_agency_type = 'MINISTERIO'
      AND upper(trim(pa.sigla)) = nm.sigla
);

WITH secretary_source(ministry_sigla, name, sigla) AS (
    VALUES
        ('AGU', 'Secretaria de Atos Normativos', 'SENOR/AGU'),
        ('AGU', 'Secretaria de Controle Interno', 'SCI/AGU'),
        ('AGU', 'Secretaria-Geral de Consultoria', 'SGCS/AGU'),
        ('AGU', 'Secretaria-Geral de Contencioso', 'SGCT/AGU'),
        ('CC', 'Secretaria de Articulação e Monitoramento', 'SAM/CC'),
        ('CC', 'Secretaria Especial de Análise Governamental', 'SAG/CC'),
        ('CC', 'Secretaria Especial do Programa de Aceleração ao Crescimento', 'SEPAC/CC'),
        ('CC', 'Secretaria Especial do Programa de Parcerias de Investimentos', 'SEPPI/CC'),
        ('CC', 'Secretaria Especial para Assuntos Jurídicos', 'SAJ/CC'),
        ('CC', 'Secretaria-Executiva - Casa Civil', 'SE/CC'),
        ('CGU', 'Secretaria de Integridade Privada', 'SIPRI/CGU'),
        ('CGU', 'Secretaria de Integridade Pública', 'SIP/CGU'),
        ('CGU', 'Secretaria Federal de Controle Interno', 'SFC/CGU'),
        ('CGU', 'Secretaria Nacional de Transparência e Acesso à Informação', 'SNAI/CGU'),
        ('CGU', 'Secretaria-Executiva - Controladoria-Geral da União', 'SE/CGU'),
        ('GSI', 'Secretaria de Acompanhamento e Gestão de Assuntos Estratégicos', 'SAGAE/GSI'),
        ('GSI', 'Secretaria de Coordenação e Assuntos Aeroespaciais', 'SCAE/GSI'),
        ('GSI', 'Secretaria de Segurança da Informação e Cibernética', 'SSIC/GSI'),
        ('GSI', 'Secretaria de Segurança Espacial', 'SPR/GSI'),
        ('GSI', 'Secretaria-Executiva - Gabinete de Segurança Institucional', 'SE/GSI'),
        ('MAPA', 'Secretaria de Comércio e Relações internacionais', 'SCRI/MAPA'),
        ('MAPA', 'Secretaria de Defesa Agropecuária', 'DAS/MAPA'),
        ('MAPA', 'Secretaria de Desenvolvimento Rural', 'SDR/MAPA'),
        ('MAPA', 'Secretaria de Política Agrícola', 'SPA/MAPA'),
        ('MAPA', 'Secretaria-Executiva - Ministério da Agricultura e Pecuária', 'SE/MAPA'),
        ('MCID', 'Secretaria Nacional de Desenvolvimento Urbano e Metropolitano', 'SNDUM/MCID'),
        ('MCID', 'Secretaria Nacional de Habitação', 'SNH/MCID'),
        ('MCID', 'Secretaria Nacional de Mobilidade Urbana', 'SEMOB/MCID'),
        ('MCID', 'Secretaria Nacional de Periferias', 'SNP/MCID'),
        ('MCID', 'Secretaria Nacional de Saneamento Ambiental', 'SNSA/MCID'),
        ('MCID', 'Secretaria-Executiva - Ministério das Cidades', 'SE/MCID'),
        ('MCOM', 'Secretaria de Radiodifusão', 'SERAD/MCOM'),
        ('MCOM', 'Secretaria de Telecomunicações', 'SETEL/MCOM'),
        ('MCOM', 'Secretaria-Executiva - Ministério das Comunicações', 'SE/MCOM'),
        ('MCTI', 'Secretaria de Ciência e Tecnologia para o Desenvolvimento Social', 'SEDES/MCTI'),
        ('MCTI', 'Secretaria de Ciência e Tecnologia para Transformação Digital', 'SETAD/MCTI'),
        ('MCTI', 'Secretaria de Desenvolvimento Tecnológico e Inovação', 'SETEC/MCTI'),
        ('MCTI', 'Secretaria de Políticas e Programas Estratégicos', 'SEPPE/MCTI'),
        ('MCTI', 'Secretaria-Executiva - Ministério da Ciência, Tecnologia e Inovação', 'SE/MCTI'),
        ('MD', 'Secretaria de Controle Interno', 'CISET/MD'),
        ('MD', 'Secretaria-Geral', 'SG/MD'),
        ('MDA', 'Companhia Nacional de Abastecimento', 'CONAB/MDA'),
        ('MDA', 'Instituto Nacional de Colonização e Reforma Agrária', 'INCRA/MDA'),
        ('MDA', 'Secretaria de Abastecimento, Cooperativismo e Soberania Alimentar', 'SEAB/MDA'),
        ('MDA', 'Secretaria de Agricultura Familiar e Agroecologia', 'SAF/MDA'),
        ('MDA', 'Secretaria de Governança Fundiária, Desenvolvimento Territorial e Socioambiental', 'SFDT/MDA'),
        ('MDA', 'Secretaria de Territórios e Sistemas produtivos Quilombolas e Tradicionais', 'SETEQ/MDA'),
        ('MDA', 'Secretaria-Executiva - Ministério do Desenvolvimento Agrário e Agricultura Familiar', 'SE/MDA'),
        ('MDHC', 'Secretaria Nacional de Promoção e Defesa dos Direitos Humanos', 'SNDH/MDHC'),
        ('MDHC', 'Secretaria Nacional dos Direitos da Criança e do Adolescente', 'SNDCA/MDHC'),
        ('MDHC', 'Secretaria Nacional dos Direitos da Pessoa com Deficiência', 'SNDPD/MDHC'),
        ('MDHC', 'Secretaria Nacional dos Direitos da Pessoa Idosa', 'SNDPI/MDHC'),
        ('MDHC', 'Secretaria Nacional dos Direitos das Pessoas LGBTQIA+', 'SLGBTQIA+/MDHC'),
        ('MDHC', 'Secretaria-Executiva - Ministério dos Direitos Humanos e da Cidadania', 'SE/MDHC'),
        ('MDIC', 'Secretaria de Comércio Exterior', 'SECEX/MDIC'),
        ('MDIC', 'Secretaria de Competitividade e Política Regulatória', 'SCPR/MDIC'),
        ('MDIC', 'Secretaria de Desenvolvimento Industrial, Inovação, Comércio e Serviços', 'SDIC/MDIC'),
        ('MDIC', 'Secretaria de Economia Verde, Descarbonização e Bioindústria', 'SEV/MDIC'),
        ('MDIC', 'Secretaria-Executiva - Ministério do Desenvolvimento, Indústria, Comércio e Serviços', 'SE/MDIC'),
        ('MDS', 'Secretaria de Avaliação, Gestão da Informação e Cadastro Único', 'SAGICAD/MDS'),
        ('MDS', 'Secretaria de Inclusão Socioeconômica', 'SISEC/MDS'),
        ('MDS', 'Secretaria Extraordinária de Combate à Pobreza e à Fome', 'SECF/MDS'),
        ('MDS', 'Secretaria Nacional da Politica de Cuidados e Família', 'SNCF/MDS'),
        ('MDS', 'Secretaria Nacional de Assistência Social', 'SNAS/MDS'),
        ('MDS', 'Secretaria Nacional de Beneficios Assistenciais', 'SNBA/MDS'),
        ('MDS', 'Secretaria Nacional de Integração e Articulação de Plataformas Sociais Eletrônicas', 'SINAPSE/MDS'),
        ('MDS', 'Secretaria Nacional de Renda de Cidadania', 'SENARC/MDS'),
        ('MDS', 'Secretaria Nacional de Segurança Alimentar e Nutricional', 'SESAN/MDS'),
        ('MDS', 'Secretaria-Executiva - Ministério do Desenvolvimento e Assistência Social, Família e Combate à Fome', 'SE/MDS'),
        ('MEC', 'Secretaria de Articulação Intersetorial e com os Sistemas de Ensino', 'SASE/MEC'),
        ('MEC', 'Secretaria de Educação Básica', 'SEB/MEC'),
        ('MEC', 'Secretaria de Educação Continuada, Alfabetização de Jovens e Adultos, Diversidade e Inclusão', 'SECADI/MEC'),
        ('MEC', 'Secretaria de Educação Profissional e Tecnológica', 'SETEC/MEC'),
        ('MEC', 'Secretaria de Educação Superior', 'SESU/MEC'),
        ('MEC', 'Secretaria de Gestão da Informação, Inovação e Avaliação de Políticas Educacionais', 'SEGAPE/MEC'),
        ('MEC', 'Secretaria de Regulação e Supervisão da Educação Superior', 'SERES/MEC'),
        ('MEMP', 'Secretaria Nacional de Ambiente de Negócios', 'SANE/MEMP'),
        ('MEMP', 'Secretaria Nacional de Inclusão Socioprodutiva, Artesanato e Microempreendedor Individual', 'SISAM/MEMP'),
        ('MEMP', 'Secretaria-Executiva - Ministério do Empreendedorismo da Microempresa e da Empresa de Pequeno Porte', 'SE/MEMP'),
        ('MESP', 'Secretaria Extraordinária da Copa do Mundo de Futebol Feminino', 'SECMFF/MESP'),
        ('MESP', 'Secretaria Nacional de Apostas Esportivas e de Desenvolvimento Econômico do Esporte', 'SNAEDE/MESP'),
        ('MESP', 'Secretaria Nacional de Esporte Amador, Educação, Lazer e Inclusão Social', 'SNEAELIS/MESP'),
        ('MESP', 'Secretaria Nacional de Excelência Esportiva', 'SNE/MESP'),
        ('MESP', 'Secretaria Nacional de Futebol e Defesa dos Direitos do Torcedor', 'SNFDT/MESP'),
        ('MESP', 'Secretaria Nacional de Paradesporto', 'SNPAR/MESP'),
        ('MESP', 'Secretaria-Executiva - Ministério do Esporte', 'SE/MESP'),
        ('MF', 'Secretaria de Assuntos internacionais', 'SAIN/MF'),
        ('MF', 'Secretaria de Política Econômica', 'SPE/MF'),
        ('MF', 'Secretaria de Prêmios e Apostas', 'SPA/MF'),
        ('MF', 'Secretaria de Reformas Econômicas', 'SER/MF'),
        ('MF', 'Secretaria do Tesouro Nacional', 'STN/MF'),
        ('MF', 'Secretaria Especial da Receita Federal do Brasil', 'RFB/MF'),
        ('MF', 'Secretaria Extraordinária do Mercado de Carbono', 'SEMC/MF'),
        ('MF', 'Secretaria-Executiva - Ministério da Fazenda', 'SE/MF'),
        ('MGI', 'Secretaria de Coordenação e Governança das Empresas Estatais', 'SEST/MGI'),
        ('MGI', 'Secretaria de Gestão de Pessoas', 'SGP/MGI'),
        ('MGI', 'Secretaria de Gestão e Inovação', 'SEGES/MGI'),
        ('MGI', 'Secretaria de Governo Digital', 'SGD/MGI'),
        ('MGI', 'Secretaria de Relações de Trabalho', 'SRT/MGI'),
        ('MGI', 'Secretaria de Serviços Compartilhados', 'SSC/MGI'),
        ('MGI', 'Secretaria do Patrimônio da União', 'SPU/MGI'),
        ('MGI', 'Secretaria Extraordinária para a Transformação do Estado', 'SETE/MGI'),
        ('MGI', 'Secretaria-Executiva - Ministério da Gestão e da Inovação em Serviços Públicos', 'SE/MGI'),
        ('MIDR', 'Secretaria Nacional de Fundos e Instrumentos Financeiros', 'SNFI/MIDR'),
        ('MIDR', 'Secretaria Nacional de Políticas de Desenvolvimento Regional e Territorial', 'SDR/MIDR'),
        ('MIDR', 'Secretaria Nacional de Proteção e Defesa Civil', 'SEDEC/MIDR'),
        ('MIDR', 'Secretaria Nacional de Segurança Hídrica', 'SNSH/MIDR'),
        ('MIDR', 'Secretaria-Executiva - Ministério da Integração e do Desenvolvimento Regional', 'SE/MIDR'),
        ('MIDR', 'Superintendência do Desenvolvimento do Centro-Oeste', 'SUDECO/MIDR'),
        ('MIDR', 'Superintendência do Desenvolvimento do Nordeste', 'SUDENE/MIDR'),
        ('MINC', 'Secretaria de Articulação Federativa e Comitês de Cultura', 'SAFCC/MINC'),
        ('MINC', 'Secretaria de Cidadania e Diversidade Cultural', 'SCDC/MINC'),
        ('MINC', 'Secretaria de Direitos Autorais e Intelectuais', 'OSDAI/MINC'),
        ('MINC', 'Secretaria de Economia Criativa', 'SEC/MINC'),
        ('MINC', 'Secretaria de Fomento e Incentivo à Cultura', 'SEFIC/MINC'),
        ('MINC', 'Secretaria de Formação Artística e Cultural, Livro e Leitura', 'SEFLI/MINC'),
        ('MINC', 'Secretaria do Audiovisual', 'SAV/MINC'),
        ('MINC', 'Secretaria-Executiva - Ministério da Cultura', 'SE/MINC'),
        ('MIR', 'Secretaria de Gestão do Sistema Nacional de Promoção da Igualdade Racial', 'SENAPIR/MIR'),
        ('MIR', 'Secretaria de Políticas de Ações Afirmativas, Combate e Superação do Racismo', 'SEPAR/MIR'),
        ('MIR', 'Secretaria de Políticas para Quilombolas, Povos e Comunidades Tradicionais de Matriz Africana, Povos de Terreiros e Ciganos', 'SQPT/MIR'),
        ('MIR', 'Secretaria-Executiva - Ministério da Igualdade Racial', 'SE/MIR'),
        ('MJSP', 'Secretaria Nacional de Acesso à Justiça', 'SAJU/MJSP'),
        ('MJSP', 'Secretaria Nacional de Assuntos Legislativos', 'SAL/MJSP'),
        ('MJSP', 'Secretaria Nacional de Direitos Digitais', 'SEDIGI/MJSP'),
        ('MJSP', 'Secretaria Nacional de Justiça', 'SENAJUS/MJSP'),
        ('MJSP', 'Secretaria Nacional de Politicas Penais', 'SENAPPEN/MJSP'),
        ('MJSP', 'Secretaria Nacional de Politicas sobre Drogas e Gestão de Ativos', 'SENAD/MJSP'),
        ('MJSP', 'Secretaria Nacional de Segurança Pública', 'SENASP/MJSP'),
        ('MJSP', 'Secretaria Nacional do Consumidor', 'SENACON/MJSP'),
        ('MJSP', 'Secretaria-Executiva - Ministério da Justiça e Segurança Pública', 'SE/MJSP'),
        ('MMA', 'Secretaria Extraordinária de Controle do Desmatamento e Ordenamento Ambiental Territorial', 'SECD/MMA'),
        ('MMA', 'Secretaria Nacional de Biodiversidade. Florestas e Direitos Animais', 'SBIO/MMA'),
        ('MMA', 'Secretaria Nacional de Bioeconomia', 'SBC/MMA'),
        ('MMA', 'Secretaria Nacional de Meio Ambiente Urbano, Recursos Hidricos e Qualidade Ambiental', 'SQA/MMA'),
        ('MMA', 'Secretaria Nacional de Mudança do Clima', 'SMC/MMA'),
        ('MMA', 'Secretaria Nacional de Povos e Comunidades Tradicionais e Desenvolvimento Rural Sustentável', 'SNPCT/MMA'),
        ('MMA', 'Secretaria-Executiva - Ministério do Meio Ambiente e Mudança do Clima', 'SE/MMA'),
        ('MME', 'Companhia de Pesquisa de Recursos Minerais', 'CPRM/MME'),
        ('MME', 'Secretaria Nacional de Energia Elétrica', 'SNEE/MME'),
        ('MME', 'Secretaria Nacional de Geologia, Mineração e Transformação Mineral', 'SNGM/MME'),
        ('MME', 'Secretaria Nacional de Petróleo, Gás Natural e Biocombustíveis', 'SNPGB/MME'),
        ('MME', 'Secretaria Nacional de Transição Energética e Planejamento', 'SNTEP/MME'),
        ('MME', 'Secretaria-Executiva - Ministério de Minas e Energia', 'SE/MME'),
        ('MMULHERES', 'Secretaria Nacional de Articulação Institucional, Ações Temáticas e Participação Política', 'SENATP/MMULHERES'),
        ('MMULHERES', 'Secretaria Nacional de Autonomia Econômica', 'SENAEC/MMULHERES'),
        ('MMULHERES', 'Secretaria Nacional de Enfrentamento à Violência contra Mulheres', 'SENEV/MMULHERES'),
        ('MMULHERES', 'Secretaria-Executiva - Ministério das Mulheres', 'SE/MMULHERES'),
        ('MPA', 'Secretaria Nacional de Aquicultura', 'SNA/MPA'),
        ('MPA', 'Secretaria Nacional de Pesca Artesanal', 'SNPA/MPA'),
        ('MPA', 'Secretaria Nacional de Pesca Industrial, Amadora e Esportiva', 'SNPI/MPA'),
        ('MPA', 'Secretaria Nacional de Registro, Monitoramento e Pesquisa da Pesca e Aquicultura', 'SERMOP/MPA'),
        ('MPA', 'Secretaria-Executiva - Ministério da Pesca e Aquicultura', 'SE/MPA'),
        ('MPI', 'Departamento de Mediação e Conciliação de Conflitos Fundiários Indígenas', 'DEMED/MPI'),
        ('MPI', 'Fundação Nacional dos Povos Indígenas', 'FUNAI/MPI'),
        ('MPI', 'Secretaria Nacional de Articulação e Promoção de Direitos Indigenas', 'SEART/MPI'),
        ('MPI', 'Secretaria Nacional de Direitos Territoriais Indigenas', 'SEDAT/MPI'),
        ('MPI', 'Secretaria Nacional de Gestão Ambiental e Territorial Indigena', 'SEGAT/MPI'),
        ('MPI', 'Secretaria-Executiva - Ministério dos Povos Indígenas', 'SE/MPI'),
        ('MPO', 'Secretaria de Articulação Institucional', 'SEAI/MPO'),
        ('MPO', 'Secretaria de Assuntos Internacionais e Desenvolvimento', 'SEAID/MPO'),
        ('MPO', 'Secretaria de Monitoramento e Avaliação de Políticas Públicas e Assuntos Econômicos', 'SMA/MPO'),
        ('MPO', 'Secretaria de Orçamento Federal', 'SOF/MPO'),
        ('MPO', 'Secretaria Nacional de Planejamento', 'SEPLAN/MPO'),
        ('MPO', 'Secretaria-Executiva - Ministério do Planejamento e Orçamento', 'SE/MPO'),
        ('MPOR', 'Secretaria Nacional de Aviação Civil', 'SAC/MPOR'),
        ('MPOR', 'Secretaria Nacional de Hidrovias e Navegação', 'SENHN/MPOR'),
        ('MPOR', 'Secretaria Nacional de Portos', 'SNP/MPOR'),
        ('MPOR', 'Secretaria-Executiva - Ministério de Portos e Aeroportos', 'SE/MPOR'),
        ('MPS', 'Secretaria de Regime Geral de Previdência Social', 'SRGPS/MPS'),
        ('MPS', 'Secretaria de Regime Próprio e Complementar', 'SRPC/MPS'),
        ('MPS', 'Secretaria-Executiva - Ministério da Previdência Social', 'SE/MPS'),
        ('MRE', 'Secretaria de Controle Interno', 'CISET/MRE'),
        ('MRE', 'Secretaria-Geral - SG', 'SG/MRE'),
        ('MS', 'Secretaria de Atenção Especializada à Saúde', 'SAES/MS'),
        ('MS', 'Secretaria de Atenção Primária à Saúde', 'SAPS/MS'),
        ('MS', 'Secretaria de Ciência, Tecnologia e Inovação em Saúde', 'SCTIE/MS'),
        ('MS', 'Secretaria de Gestão do Trabalho e da Educação na Saúde', 'SGTES/MS'),
        ('MS', 'Secretaria de Informação e Saúde Digital', 'SEIDIGI/MS'),
        ('MS', 'Secretaria de Saúde Indígena', 'SESAI/MS'),
        ('MS', 'Secretaria de Vigilância em Saúde e Ambiente', 'SVSA/MS'),
        ('MS', 'Secretaria-Executiva - Ministério da Saúde', 'SE/MS'),
        ('MT', 'Secretaria Nacional de Trânsito', 'SENATRAN/MT'),
        ('MT', 'Secretaria Nacional de Transporte Ferroviário', 'SNTF/MT'),
        ('MT', 'Secretaria Nacional de Transporte Rodoviário', 'SNTR/MT'),
        ('MT', 'Secretaria-Executiva - Ministério dos Transportes', 'SE/MT'),
        ('MTE', 'Secretaria de Inspeção do Trabalho', 'SIT/MTE'),
        ('MTE', 'Secretaria de Proteção ao Trabalhador', 'SPT/MTE'),
        ('MTE', 'Secretaria de Relações do Trabalho', 'SRT/MTE'),
        ('MTE', 'Secretaria Nacional de Economia Popular e Solidária', 'SENAES/MTE'),
        ('MTE', 'Secretaria Nacional de Qualificação, Emprego e Juventude', 'SEQ/MTE'),
        ('MTE', 'Secretaria-Executiva - Ministério do Trabalho e Emprego', 'SE/MTE'),
        ('MTUR', 'Secretaria Nacional de Infraestrutura, Crédito e Investimento no Turismo', 'SNINFRA/MTUR'),
        ('MTUR', 'Secretaria Nacional de Políticas de Turismo', 'SNPTur/MTUR'),
        ('MTUR', 'Secretaria-Executiva - Ministério do Turismo', 'SE/MTUR'),
        ('SECOM', 'Secretaria de Comunicação Institucional', 'SECOI/SECOM'),
        ('SECOM', 'Secretaria de Estratégias e Redes', 'SERES/SECOM'),
        ('SECOM', 'Secretaria de Imprensa', 'SIMP/SECOM'),
        ('SECOM', 'Secretaria de Políticas Digitais', 'SPDIGI/SECOM'),
        ('SECOM', 'Secretaria de Produção e Divulgação de Conteúdo Audiovisual', 'SEAUD/SECOM'),
        ('SECOM', 'Secretaria de Publicidade e Patrocínios', 'SPP/SECOM'),
        ('SECOM', 'Secretaria-Executiva - Secretaria de Comunicação Social', 'SE/SECOM'),
        ('SGPR', 'Secretaria Nacional de Diálogos Sociais e Articulação de Politicas Públicas', 'SNDS/SGPR'),
        ('SGPR', 'Secretaria Nacional de Juventude', 'SNJ/SGPR'),
        ('SGPR', 'Secretaria Nacional de Participação Social', 'SNPS/SGPR'),
        ('SGPR', 'Secretaria Nacional de Relações Politico-Sociais', 'SNRPS/SGPR'),
        ('SGPR', 'Secretaria-Executiva - Secretaria-Geral da Presidência', 'SE/SGPR'),
        ('SGPR', 'Secretaria-Executiva da Comissão Nacional de Agroecologia e Produção Orgànica', 'SECNAPO/SGPR'),
        ('SGPR', 'Secretaria-Executiva da Comissão Nacional de População em Desenvolvimento', 'SECNPD/SGPR'),
        ('SGPR', 'Secretaria-Executiva do Comitê Intermisterial para Inclusão Socioeconômica de Catadoras e Catadores de Materia', 'SECIISC/SGPR'),
        ('SGPR', 'Secretaria-Executiva do Conselho Nacional de Fomento e Colaboração', 'SECONFOCO/SGPR'),
        ('SGPR', 'Secretaria-Executiva do Conselho Nacional de Juventude', 'SECNJ/SGPR'),
        ('SGPR', 'Secretaria-Executiva do Conselho Nacional de Segurança Alimentar e Nutricional', 'SECONSEA/SGPR'),
        ('SRI', 'Secretaria Especial de Acompanhamento Governamental', 'SEAG/SRI'),
        ('SRI', 'Secretaria Especial de Assuntos Federativos', 'SEAF/SRI'),
        ('SRI', 'Secretaria Especial de Assuntos Parlamentares', 'SEPAR/SRI'),
        ('SRI', 'Secretaria-Executiva - Secretaria de Relações Institucionais', 'SE/SRI'),
        ('SRI', 'Secretaria-Executiva do Conselho da Federação', 'SE/Conselho/SRI')
), normalized_secretary AS (
    SELECT
        upper(regexp_replace(trim(ministry_sigla), '\s+', '', 'g')) AS ministry_sigla,
        regexp_replace(trim(name), '\s+', ' ', 'g') AS name,
        NULLIF(regexp_replace(trim(sigla), '\s+', '', 'g'), '') AS sigla
    FROM secretary_source
), ministry_lookup AS (
    SELECT ns.*, pa.id AS public_agency_id
    FROM normalized_secretary ns
    JOIN public_agencies pa
      ON pa.public_agency_type = 'MINISTERIO'
     AND upper(trim(pa.sigla)) = ns.ministry_sigla
), updated_secretary AS (
    UPDATE secretariats s
    SET
        sigla = ml.sigla,
        is_client = TRUE,
        is_active = TRUE,
        updated_at = NOW(),
        updated_by = COALESCE(s.updated_by, 1)
    FROM ministry_lookup ml
    WHERE s.public_agency_id = ml.public_agency_id
      AND upper(trim(s.name)) = upper(ml.name)
    RETURNING s.id
)
INSERT INTO secretariats (
    code, sigla, public_agency_id, name, cnpj, is_client,
    email, phone, address, contact_person, is_active, created_by, created_at
)
SELECT
    NULL,
    ml.sigla,
    ml.public_agency_id,
    ml.name,
    NULL,
    TRUE,
    NULL, NULL, NULL, NULL,
    TRUE,
    1,
    NOW()
FROM ministry_lookup ml
WHERE NOT EXISTS (
    SELECT 1
    FROM secretariats s
    WHERE s.public_agency_id = ml.public_agency_id
      AND upper(trim(s.name)) = upper(ml.name)
);

